version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: app
    volumes:
      - './app:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    command: [sh, -c, npm run dev]
